# Generated by Django 5.1.2 on 2024-12-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_recolectada', models.FloatField(help_text='Cantidad de residuos recolectados en kg')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to='dashboard.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to='dashboard.vehiculo')),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'ordering': ['fecha'],
            },
        ),
    ]
