# Generated by Django 5.1.2 on 2024-12-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
